
version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: src/Dockerfile
      target: publish
    ports:
      - "5001:5001"
    depends_on:
      - drawerdb
    # Overrides default command so things don't shut down after the process ends.
    # command: sleep infinity
    #network_mode: service:drawerdb
    
  drawerdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    expose:
      - 1433
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
