/*

Deployment script for DrawDb

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "DrawDb_LM"
:setvar DefaultFilePrefix "DrawDb_LM"
:setvar DefaultDataPath "/var/opt/mssql/data/"
:setvar DefaultLogPath "/var/opt/mssql/data/"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating database $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)]
    ON 
    PRIMARY(NAME = [$(DatabaseName)], FILENAME = N'$(DefaultDataPath)$(DefaultFilePrefix)_Primary.mdf')
    LOG ON (NAME = [$(DatabaseName)_log], FILENAME = N'$(DefaultLogPath)$(DefaultFilePrefix)_Primary.ldf') COLLATE Latin1_General_BIN2
GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating SqlTable [dbo].[Countries]...';


GO
CREATE TABLE [dbo].[Countries] (
    [Id]   INT           NOT NULL,
    [Name] NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating SqlTable [dbo].[Teams]...';


GO
CREATE TABLE [dbo].[Teams] (
    [Id]        INT           NOT NULL,
    [Name]      NVARCHAR (50) NOT NULL,
    [CountryId] INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating SqlForeignKeyConstraint unnamed constraint on [dbo].[Teams]...';


GO
ALTER TABLE [dbo].[Teams]
    ADD FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Countries] ([Id]);

GO
PRINT N'Creating SqlTable [dbo].[DrawResults]...';


GO

CREATE TABLE [dbo].[DrawResults]
(
  [Id] INT  IDENTITY(1,1) NOT NULL PRIMARY KEY,
  [DrawRequest] NTEXT NOT NULL,
  [Results] NTEXT NOT NULL
)


GO
PRINT N'Insering data to SqlTable [dbo].[Countries]...';


insert into [dbo].[Countries] ([Id], [Name]) values (1, 'Germany');
insert into [dbo].[Countries] ([Id], [Name]) values (2, 'Turkey');
insert into [dbo].[Countries] ([Id], [Name]) values (3, 'France');
insert into [dbo].[Countries] ([Id], [Name]) values (4, 'Netherlands');
insert into [dbo].[Countries] ([Id], [Name]) values (5, 'Portugal');
insert into [dbo].[Countries] ([Id], [Name]) values (6, 'Italy');
insert into [dbo].[Countries] ([Id], [Name]) values (7, 'Spain');
insert into [dbo].[Countries] ([Id], [Name]) values (8, 'Belgium');

GO
PRINT N'Insering data to SqlTable [dbo].[Teams]...';

insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (1, 'Berlin', 1);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (2, 'Frankfurt', 1);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (3, 'Münih', 1);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (4, 'Dortmund', 1);

insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (5, 'Istanbul', 2);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (6, 'Ankara', 2);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (7, 'Izmir,', 2);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (8, 'Antalya', 2);

insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (9, 'Paris', 3);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (10, 'Marsilya', 3);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (11, 'Nice', 3);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (12, 'Lyon', 3);

insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (13, 'Amsterdam', 4);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (14, 'Rotterdam', 4);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (15, 'Lahey', 4);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (16, 'Eindhoven', 4);

insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (17, 'Lisbon', 5);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (18, 'Porto', 5);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (19, 'Braga', 5);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (20, 'Coimbra', 5);

insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (21, 'Roma', 6);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (22, 'Milano', 6);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (23, 'Napoli', 6);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (24, 'Venedik', 6);

insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (25, 'Madrid', 7);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (26, 'Barcelona', 7);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (27, 'Sevilla', 7);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (28, 'Granada', 7);

insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (29, 'Brussels', 8);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (30, 'Brugge', 8);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (31, 'Ghent', 8);
insert into [dbo].[Teams] ([Id], [Name], [CountryId]) values (32, 'Anvers', 8);

GO
PRINT N'Database update complete.';

GO
